name = "StoppingTutorials"
uuid = "b1001b4c-0346-4072-8a18-8b9eb10a72ff"
authors = ["Tangi Migot tangi.migot@gmail.com"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Stopping = "c4fe5a9e-e7fb-5c3d-89d5-7f405ab2214f"

[compat]
Literate = "2"
DataFrames = "1"
Plots = "1"
Stopping = "0.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
